version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vault.home.arpa
      - SIGNUPS_ALLOWED=true
    volumes:
      - ./data:/data
    ports:
      - "8080:80"